// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEUOjAUQw43qv-3AQU_vk-DB7Xq1TEI4',
    appId: '1:742196104477:web:afc89703d10e91e3e9e5f4',
    messagingSenderId: '742196104477',
    projectId: 'to-do-list-b75af',
    authDomain: 'to-do-list-b75af.firebaseapp.com',
    databaseURL: 'https://to-do-list-b75af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-b75af.appspot.com',
    measurementId: 'G-BW51EX11GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-1To_pb2f06FlXID_pxPATTFoWeXP3A',
    appId: '1:742196104477:android:6b365488103bbd19e9e5f4',
    messagingSenderId: '742196104477',
    projectId: 'to-do-list-b75af',
    databaseURL: 'https://to-do-list-b75af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-b75af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYg1GLSlX11RBysqt9eOKz8_3OKm5wK5Y',
    appId: '1:742196104477:ios:97adc4a2e21d4594e9e5f4',
    messagingSenderId: '742196104477',
    projectId: 'to-do-list-b75af',
    databaseURL: 'https://to-do-list-b75af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-b75af.appspot.com',
    androidClientId: '742196104477-o5ami5rh7oot06jq9070u54a2q8fg0fj.apps.googleusercontent.com',
    iosClientId: '742196104477-fies0s6q3melknj3t136mv7a8thdk74e.apps.googleusercontent.com',
    iosBundleId: 'com.yavuz.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYg1GLSlX11RBysqt9eOKz8_3OKm5wK5Y',
    appId: '1:742196104477:ios:adf3ca1850e87068e9e5f4',
    messagingSenderId: '742196104477',
    projectId: 'to-do-list-b75af',
    databaseURL: 'https://to-do-list-b75af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-b75af.appspot.com',
    androidClientId: '742196104477-o5ami5rh7oot06jq9070u54a2q8fg0fj.apps.googleusercontent.com',
    iosClientId: '742196104477-9cq56r0sn2baihhmrif3vou68h52irir.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAEUOjAUQw43qv-3AQU_vk-DB7Xq1TEI4',
    appId: '1:742196104477:web:20f1d848a5d41271e9e5f4',
    messagingSenderId: '742196104477',
    projectId: 'to-do-list-b75af',
    authDomain: 'to-do-list-b75af.firebaseapp.com',
    databaseURL: 'https://to-do-list-b75af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-b75af.appspot.com',
    measurementId: 'G-7PVH881WFH',
  );
}
